---
- hosts: jyboss

  roles:
    - ansible-java
    - ansible-jython
    - ansible-jyboss
    - ansible-wildfly

  tasks:
    - name: Connect to JBoss For Facts
      jboss:
        jboss_home: "{{ jboss_home }}"
        config_file: "standalone-ha.xml"
        domain_mode: no
        embedded_mode: yes
        server_name: default-server
        host_name: default-host
        facts: yes
      tags: ['jboss']

    - name: Check what we got from the JEE server retrieved by the JyBoss Module
      debug: var=jboss
      tags: ['jboss']

    - name: Update Undertow Filters
      jboss:
        jboss_home: "{{ jboss_home }}"
        config_file: "standalone-ha.xml"
        domain_mode: no
        embedded_mode: yes
        server_name: default-server
        host_name: default-host
        custom_filter:
          - name: proxy-peer
            state: present
            class_name: "io.undertow.server.handlers.ProxyPeerAddressHandler"
            module: "io.undertow.core"
          - name: request-dumper
            state: present
            class_name: "io.undertow.server.handlers.RequestDumpingHandler"
            module: "io.undertow.core"
            priority: 30

      tags: ['jboss']