---
galaxy_info:
  author: Niels Bertram
  description: Java Role
  license: "license (Apache 2.0)"
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
      - xenial
      - precise
      - trusty
  categories:
    - java
