---

# `download_dir` the directory on the target host where the module will by downloaded to

- name: Check Module Parameter
  fail: msg="module parameter not provided to download-remote.yml task"
  when: module is undefined

- name: Check URL Parameter
  fail: msg="url parameter not provided to download-remote.yml task"
  when: url is undefined

- name: "Check {{ module }} Downloaded"
  stat: path="{{ download_dir | default('/tmp') }}/{{ module }}"
  register: module_download_check

- name: Ensure Remote Download Location Exists
  file: path="{{ download_dir | default('/tmp') }}" state=directory

- name: "Download {{ module }}"
  get_url: url="{{ url }}" dest="{{ download_dir | default('/tmp') }}/{{ module }}" headers="{{ headers|default([])|join(',') }}"
  when: not module_download_check.stat.exists
