---

# `local_download_dir` the directory where the module will be downloaded to
# `download_dir` the directory on the target host where the module will by synched to

- name: Check Module Parameter
  fail: msg="module parameter not provided to download-local.yml task"
  when: module is undefined

- name: Check URL Parameter
  fail: msg="url parameter not provided to download-local.yml task"
  when: url is undefined

- name: Ensure Local Download Location Exists
  become: no
  local_action: >
    file path="{{ local_download_dir | default('~/Downloads') }}" state=directory

- name: "Check {{ module }} Downloaded"
  become: no
  local_action: >
    stat path="{{ local_download_dir | default('~/Downloads') }}/{{ module }}"
  register: module_download_check

- name: "Download {{ module }}"
  become: no
  local_action: >
    get_url url="{{ url }}" dest="{{ local_download_dir | default('~/Downloads') }}/{{ module }}" headers="{{ headers|default([])|join(',') }}"
  when: not module_download_check.stat.exists

- name: Ensure Download Location on Target Host Exists
  file: path="{{ download_dir | default('/tmp') }}" state=directory

- name: "Copy {{ module }} to Target Host"
  copy:
    src: "{{ local_download_dir|default('~/Downloads') }}/{{ module }}"
    dest: "{{ download_dir | default('/tmp') }}/{{ module }}"
