---
# Include OS specific variables and define needed variables
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"

- name: Download Java Installer
  include: dl/download-{{ dl_mode | default('local') }}.yml
  when: ansible_os_family in [ 'RedHat', 'Windows', 'Darwin' ]
  vars:
    module: "{{ java_distro }}"
    url: "{{ java_url }}"
    header:
      - "Cookie:oraclelicense=accept-securebackup-cookie"

# ubuntu works a bit different, install from repo directly
- include: dl/download-Ubuntu.yml
  when: ansible_distribution in [ 'Ubuntu' ]

# Install Java on the target platform
- include: 02-jdk-install.yml
